stages:
  convert:
    cmd: python3 preprocess/convert_labels.py
    deps:
      - preprocess/raw_labels
      - preprocess/convert_labels.py
  split:
    cmd: python3 preprocess/train_test_split.py --dvc
    params:
      - split.val_size
      - split.test_size
    deps:
      - preprocess/raw_images
      - dataset/grain_data/labels
      - preprocess/train_test_split.py
    outs:
      - dataset/grain_data/train
      - dataset/grain_data/test
  train:
    cmd: python3 train.py --img 1024 --batch 1 --data data.yaml --weights yolov5s.pt --dvc
    params:
      - train.epochs
    deps:
      - dataset/grain_data/train
      - dataset/grain_data/test
      - dataset/grain_data/val
      - data/hyps/hyp.scratch-low.yaml
      - data/hyps/hyp.scratch-med.yaml
      - data/hyps/hyp.scratch-high.yaml
      - train.py
